apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hasura-engine.fullname" . }}
  labels:
    {{- include "hasura-engine.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "hasura-engine.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "hasura-engine.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hasura-engine.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: HASURA_GRAPHQL_DATABASE_URL
              value: "postgres://{{ .Values.database.user }}:{{ .Values.database.password }}@{{ .Values.database.address }}:{{ .Values.database.port }}/{{ .Values.database.dbName }}"
            - name: HASURA_GRAPHQL_METADATA_DATABASE_URL
              value: "postgres://{{ .Values.metadataDatabase.user }}:{{ .Values.metadataDatabase.password }}@{{ .Values.metadataDatabase.address }}:{{ .Values.metadataDatabase.port }}/{{ .Values.metadataDatabase.dbName }}"
            {{ if trim .Values.hasura.adminSecret }}
            - name: HASURA_GRAPHQL_ADMIN_SECRET
              value: {{ trim .Values.hasura.adminSecret | quote }}
            - name: HASURA_GRAPHQL_ENABLE_CONSOLE
              value: {{ .Values.hasura.enableConsole | quote }}
            {{ end }}
            - name: HASURA_GRAPHQL_ENABLED_LOG_TYPES
              value: "startup"
            - name: HASURA_GRAPHQL_LOG_LEVEL
              value: "error"
            - name: HASURA_GRAPHQL_DEV_MODE
              value: "false"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
