type LabelsResult {
  name: String!
  content: String!
  source: String!
}

type AddressResult {
  value: String!
  is_contract: Boolean!
  friend_request: FriendRequestResult
}

type FriendRequestResult {
  from: String!
  to: String!
  status: Int!
}

type AddressWithLabelsResult {
  id: Int!
  address: AddressResult!
  labels: LabelsResult!
  user_name: String
  user_introduction: String
  hasCollect: Int
}

type Query {
  labels_query_addresses_action(
    base_id: Int
    labels: [String!]
    mode: String!
    limit: Int
  ): [AddressWithLabelsResult]
}

type Query {
  address_query_labels_action(address: String!): [AddressWithLabelsResult]
}

type Query {
  label_popular_action: LabelPopularActionResult
}

type LabelPopularActionResult {
  dataList: LabelPopularItemActionResult!
  total: Int
}

type LabelPopularItemActionResult {
  id: Int
  owner: String
  type: String
  name: String
  source: String
  content: String
}

type DictionaryDescribeActionResult {
  englishDescribe: String
  hasCollect: Int
  collectionCount: Int
  labelId: Int
  source: String
  userName: String
  userDescribe: String
  refreshTime: Int
}

type Query {
  dictionary_describe_action(
    assetId: Int!
    dictId: Int!
    projectId: Int
    tradeTypeId: Int
  ): DictionaryDescribeActionResult
}

type Query {
  dictionary_describe_label_name_action(
    labelName: String!
  ): DictionaryDescribeActionResult
}

type LabelsCountActionResult {
  count: Int!
}

type Query {
  labels_count_action(labels: [String!], mode: String!): LabelsCountActionResult
}

type Query {
  friends_action(
    from: String!
    keyword: String
    limit: Int
    offset: Int
  ): FriendsOutput
}

type FriendsOutput {
  count: Int!
  results: [FriendsRecord]
}

type FriendsRecord {
  name: String
  labels: [String]
  address: String
  introduction: String
  created_at: String
}

type Query {
  friends_request_action(
    address: String!
    status: [Int]
    limit: Int
    offset: Int
  ): FriendsRequestOutput
}

type FriendsRequestOutput {
  count: Int!
  results: [FriendsRequestRecord]
}

type FriendsRequestRecord {
  from: String!
  to: String!
  status: Int!
  name: String
  introduction: String
  updated_at: String
}

type Query {
  query_by_address_action(
    from: String
    address: String!
  ): [AddressWithLabelsResult]
}

type Query {
  query_by_labels_action(
    from: String
    base_id: Int
    labels: [String!]
    mode: String!
    limit: Int
  ): [AddressWithLabelsResult]
}
