type LabelsResult {
  name: String!
  content: String!
  source: String!
}

type AddressWithLabelsResult {
  id: Int!
  address: String!
  labels: LabelsResult!
  user_name: String
  user_introduction: String
  hasCollect: Int
}

type Query {
  labels_query_addresses_action(
    base_id: Int
    labels: [String!]
    mode: String!
    limit: Int
  ): [AddressWithLabelsResult]
}

type Query {
  address_query_labels_action(address: String!): [AddressWithLabelsResult]
}

type Query {
  label_popular_action: LabelPopularActionResult
}

type LabelPopularActionResult {
  dataList: LabelPopularItemActionResult!
}

type LabelPopularItemActionResult {
  id: Int
  owner: String
  type: String
  name: String
  source: String
}

type DictionaryDescribeActionResult {
  chineseDescribe: String
  englishDescribe: String
  hasCollect: Int
  collectionCount: Int
  labelId: Int
}

type Query {
  dictionary_describe_action(
    assetId: Int!
    dictId: Int!
    projectId: Int
    tradeTypeId: Int
  ): DictionaryDescribeActionResult
}

type Query {
  dictionary_describe_label_name_action(
    labelName: String!
  ): DictionaryDescribeActionResult
}

type LabelsCountActionResult {
  count: Int!
}

type Query {
  labels_count_action(labels: [String!], mode: String!): LabelsCountActionResult
}
